allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  leveldown: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - leveldown
  - unrs-resolver
